//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frequency.Edu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Trainees = new HashSet<Trainee>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public decimal CourseFees { get; set; }
        public string Schedule { get; set; }
        public string CourseDuration { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<int> ExamDetailID { get; set; }
    
        public virtual ExamDetail ExamDetail { get; set; }
        public virtual Trainer Trainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainee> Trainees { get; set; }
    }
}
